server:
  port: 9498
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thakurjay1/microservices-configuration 
          clone-on-start: true 